### PR TITLE
Fix #40 - Check operating system family

### LINKED ISSUE #40: Check the Operating System
We could check the Operating System (in our case Debian-based) before running the playbook to prevent the user from running it against an unsupported OS.

### PR DESCRIPTION
**Pull request by awailly**
- Added first check in tasks/main.yml for ansible_os_family
- Removed unused file

### CODE REVIEW

**Comment by pchaigno** [comment]
We could probably check this condition too while we're at it:

``` python
ansible_version.full | version_compare('1.8', '>=')
```

**Comment by pchaigno** [comment]
Maybe we should put these preconditions in a separate file (as we do for each section). We might want to add new conditions in the future (grub for instance).

**Comment by awailly** [comment]
@pchaigno, do you mind doing it in the yml file ? :) That way you will do all the checks in one shot, which is better than me patching with your comments.

**Comment by pchaigno** [comment]
Sure. I just wanted to make sure that you didn't have a reason for doing otherwise.

**Comment by pchaigno** [comment]
:+1:

**Pull request merged**
