### PR TITLE
Add default values for the with_item values for 13.18.

### LINKED ISSUE #89: Role fails to run if skipped
When the role is skipped, eg

```
  - role: cis
    when: some_variable_that_is_false
```

A 13.18 fails with

```
TASK: [cis | 13.18 Check for Presence of User .netrc Files (stat) (Scored)] ***
fatal: [10.0.139.165] => with_items expects a list or a set
fatal: [10.0.136.68] => with_items expects a list or a set
fatal: [10.0.137.117] => with_items expects a list or a set
```

This may or not be problem with ansible 2.0, but it is with 1.9.x. 

To handle this case the two 13.8 with_item values need to be changed to

```
    with_items: '{{ home_users.stdout_lines | default([]) }}'
    ...
    with_items: '{{ netrc_files.results | default([]) }}'
```

Why ever skip cis? When adding new nodes a cluster (eg, a new mesos-slave node) I will run the entire cluster playbook. The new node gets created and provisioned, but all the other nodes run too. Of course with good playbooks that's just a bunch of 'oks'. 

But with some type of nodes, for some of the cis tasks that check files or permissions, there are so many files to check that the playbook can take hours to complete. The mesos-slave for example, is runnign lots of docker containers and other mesos containers and will have a gazzilion data files. For these nodes, I set a value in `/etc/ansible/facts.d/cis_ubuntu.fact` indicating that cis has already run and not to do it again. 

PR on the way.

### PR DESCRIPTION
**Pull request by memelet**
Add default empty array value for the with_item values for 13.18. 
resolves #89

### CODE REVIEW

**Comment by awailly** [comment]
Waiting for comments in #89 before merging.

**Comment by pchaigno** [comment]
We should also add a test for this in `.travis.yml`.

**Comment by awailly** [comment]
I am not sure on how we can test this. Can you show the high level idea?

**Comment by pchaigno** [comment]
In `.travis.yml`, we currently have 3 tests configured: a syntax check, [the main test](https://github.com/awailly/cis-ubuntu-ansible/blob/master/.travis.yml#L38) and an idempotence check. For the main test, we use a [pretty simple playbook](https://github.com/awailly/cis-ubuntu-ansible/blob/master/tests/playbook.yml). We could add a fourth test with a playbook that skips the CIS role as in @memelet's example in #89; something like:

``` yaml
---
- hosts: all
  roles:
    - cis-ubuntu-ansible
  when: False
```

**Comment by memelet** [comment]
Is there something I need to do that is blocking this merge?

**Comment by awailly** [comment]
Should be fixed with #108.

**Pull request closed without merging**
