### PR TITLE
Flush routing table from cache

### PR DESCRIPTION
**Pull request by cpliakas**
After running this role, the `7.2.4 Log Suspicious Packets` and `7.2.8 Enable TCP SYN Cookies` benchmarks are failing according to the [The CIS-CAT Benchmark Assessment Tool](https://benchmarks.cisecurity.org/downloads/audit-tools/#cis-cat) because the routing tables aren't flushed from cache after the changes are applied. The benchmarks continue to fail even after the system is restarted.

This pull request results in the benchmarks passing.

### CODE REVIEW

**Comment by pchaigno** [comment]
> The benchmarks continue to fail even after the system is restarted.

That's a bit weird :/
Isn't routing table cache cleared on reboots?

**Comment by awailly** [comment]
Yes the reboot routing tables is awkward. Still, this is a good enhancement. Do you mind renaming the step to `- name: 7.2.4.3 Log Suspicious Packets (flushing tables) (Scored)` to keep track of what is happening while running the role?

**Comment by cpliakas** [comment]
@pchaigno After looking into this further, I suspect that this is more of an issue with the CIS-CAT Benchmark Assessment Tool. I'd bet that the recommendations are being met and the routing table cache is flushed on reboot, but for some reason the assessment tool fails if the `net.ipv4.route.flush` parameter isn't set to `1`. Even if that is the case, for me generating a clean report is helpful so that I don't have to explain the exception :-).

Made the recommended change to the name, thanks for being receptive to this PR.

**Comment by pchaigno** [comment]
> Even if that is the case, for me generating a clean report is helpful so that I don't have to explain the exception :-).

I think we also want to apply changes without reboots as much as possible :+1:

**Pull request merged**
