### PR TITLE
Replace Hardcoded Grub Password

### PR DESCRIPTION
**Pull request by fti7**
Thanks for this Playbook.
Unfortunately i found an Hardcoded Grub Password :-(
This PR will move it to an own Variable

### CODE REVIEW

**Comment by awailly** [comment]
Nice spot! I will check for the integration and then push.

**Comment by awailly** [comment]
@fti7 Do you mind merging the last version of master to remove the out-of-date warning ?

**Comment by fti7** [comment]
Done :-)

**Comment by pchaigno** [comment]
Thanks @fti7!

**Comment by awailly** [comment]
Awesome, thank you.

**Pull request merged**
