### PR TITLE
Wip/issue Fix #101

### LINKED ISSUE #101: 2.17.2 Set Sticky Bit on All World-Writable Directories fails is no files found
If section 2.17 is skipped section 2.17.2 will result in the following error:

```
TASK: [cis | 2.17.2 Set Sticky Bit on All World-Writable Directories (Scored)] ***
fatal: [10.0.139.156] => with_items expects a list or a set
fatal: [10.0.136.223] => with_items expects a list or a set
```

This is really a general problem with ansible (at least with 1.9) in that even though a task is skipped its with_items is still evaluated.

### PR DESCRIPTION
**Pull request by memelet**
resolves issue-101

### CODE REVIEW

**Comment by awailly** [comment]
Thanks for the PR! The fixes are applied to all Ansible commands using `with_items`. However the issue described in #101 only affect the commands using `with_items` and `when`.

The issue is described in http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement. I don't think we need to add extra characters to non-affected code.

If you agree with what I just said, can you update the PR to only apply the fix to the subset of commands using `with_items` and `when` at the same time? Otherwise, happy to hear why it should be merged as-is.

**Comment by memelet** [comment]
I was not aware that it was just for with_items with whens. I kept hitting these one at a time so I just broke down and adjusted then all. 

I will update the PR to limit the scope.

**Comment by awailly** [comment]
Awesome thank you, we will merge when you commit.

**Comment by memelet** [comment]
The docs you sited describe a different scenario. It is saying how to protect to the expression in the _when_ clause by providing a default for the with_items. That is the not problem of this issue. In this case it is the expression in the with_items itself that is causing the problem. Specifically that the nested attribute is not defined, eg from 2.17.2:

  with_items: "{{sticky_bit_dirs.stdout_lines}}"

When the 2.17.1 is skipped there is no value for sticky_bit_dirs and hence the evaluation of {{sticky_bit_dirs.stdout_lines}} fails. Adding '|default([])' prevents the expression evaluation from failing. The when has no part in this.

All the above is for ansible 1.9. I'm finding that with ansible 2.1 these errors no longer occur. I suppose this is due the now lazy evaluation of tasks wrt to tags and skips. And since I am nearly ready to switch over to 2.1, and it seems that I am only user that encounters this problem, I'm going to hold off on this PR, and most probably withdraw it sometime next week.

**Comment by pchaigno** [comment]
> Thanks for the PR! The fixes are applied to all Ansible commands using `with_items`. However the issue described in #101 only affect the commands using `with_items` and `when`.

@awailly Actually @memelet is correct (last comment). I just ran into this issue for a task that doesn't have a `when` statement (`10.2` under Ansible 1.9.1).

However, I do not think this pull request is the proper fix. This is happening because some _check tasks_ do not have a `always_run` statement. See [`10.2`](https://github.com/awailly/cis-ubuntu-ansible/blob/ac6f45fca97460eafd44e25b72522a4e0949d4d4/tasks/section_10_level1.yml#L34) for an example. Because the _check task_ is not always run (not in check mode), the variable it registers is not ready for the subsequent _main task_.
I'll open a pull request to fix that.

**Comment by awailly** [comment]
Ok, thanks. @memelet can you confirm that the fix @pchaigno proposed is the correct fix?

**Comment by memelet** [comment]
I was not aware of `always_run`. @pchaigno, does that also apply for when a task is excluded via tags? My scenario was not because of check mode, but rather because some tasks were excluded due to tags.

**Comment by pchaigno** [comment]
Okay, I can reproduce by skipping `2.17.1`.
I think it shouldn't be possible to skip `2.17.1` without skipping `2.17.2` too. Actually, `2.17.1` is a _check task_ for `2.17.2` but it doesn't follow the same naming conventions as other _check tasks_. I'll fix that.

**Comment by pchaigno** [comment]
Closing in favor of #108.

**Pull request closed without merging**
