### PR TITLE
Add follow=yes when checking dot file permissions in 13.8.2 so the ta…

### LINKED ISSUE #78: 13.8.2 Check User Dot File Permissions fails if dot file is a link
eg, 

```
failed: [10.0.192.55] => (item=/home/barry/.zprofile) => {"failed": true, "item": "/home/barry/.zprofile"}
msg: src and dest are required for creating links
failed: [10.0.192.55] => (item=/home/barry/.zshenv) => {"failed": true, "item": "/home/barry/.zshenv"}
msg: src and dest are required for creating links
```

### PR DESCRIPTION
**Pull request by memelet**
…sk does not error for symlinks

Closes #78

### CODE REVIEW

**Comment by memelet** [comment]
Did the travis build fail because of something I did or didn't do?

**Comment by pchaigno** [comment]
@memelet The Travis build is failing because our playbook is not compatible with Ansible 2.0 yet (see #75), so not because of what you changed ;)

@awailly Maybe we could merge #76, since the tests are failing anyway. It would allow us to see whether the tests are passing for Ansible 1.9.1.

**Comment by awailly** [comment]
We need to fix #75 before merging #76. I don't like the "failing anyway" part of your sentence, let me figure this out.

**Comment by awailly** [comment]
@memelet Do you mind updating the PR against the latest branch? Thanks!

**Pull request merged**
