### PR TITLE
Command line utility for deployment

### PR DESCRIPTION
**Pull request by pchaigno**
We mentioned at some point (probably on IRC though) that we could have a Bash script for deployment distributed with the [releases](https://github.com/awailly/cis-ubuntu-ansible/releases).

The goal is to have a simple command line utility for users who want to test this without the _burden_ of installing Ansible, reading the documentation, etc. So the script should install everything, set up the environment and present clear choices to the user (such as Desktop/Server, Remote log/Local logs).

I'm opening this issue to see what this script should do exactly.
What I listed so far:
- [x] Download the repository.
- [x] [Set up the environment](https://github.com/awailly/cis-ubuntu-ansible#setting-up-the-environment).
- [x] Install Ansible and aptitude if needed.
- [x] Tune the environment (or it could assume that its a default Desktop config):
  - Desktop/Server (`remove_xserver`)
  - Remote logs (`send_rsyslog_remote`)
  - Is the system partitioned? (`partitioning`)
- [x] Run the playbook.

### CODE REVIEW

**Comment by pchaigno** [comment]
I just turned this issue into a pull request that adds steps in the README. The script itself in on the `install` branch (which is based on the initial commit).
@awailly @SpoonBoy Could you check that it works on your side too before merging this?

We should probably have something before `Usage` explaining succinctly what the playbook will change on the system...

**Comment by awailly** [comment]
Nice @pchaigno ! I setup systems and tell you asap.

**Comment by awailly** [comment]
I had to update the `install` branch with update and new dependencies. There is still a bug anyway, I have to _run it three times_ before reaching the `ansible-playbook` command. It looks like the `apt-get upgrade` command run after the call to ansible commands.

Tell me if you need more debug ;)

**Comment by awailly** [comment]
Also, if the ansible-playbook completes, a new run will fail with 

```
fatal: destination path 'roles/cis' already exists and is not an empty directory.
```

**Comment by pchaigno** [comment]
> I had to update the install branch with update and new dependencies.

That's weird but I guess it doesn't hurt :/
`markupsafe` is automatically installed by `pip` for me. There are some warnings related to the absence of `python-dev` during the installation but it still succeeds.
Are you testing on Ubuntu Server 14.04? (I'm testing on Desktop).

> There is still a bug anyway, I have to run it three times before reaching the ansible-playbook command.

I think I had a similar bug (I had to run it twice) but I can't reproduce it now... Could this have something to do with the here string part?

> It looks like the apt-get upgrade command run after the call to ansible commands.

What `apt-get upgrade`?? Do you have a log file?

> Also, if the ansible-playbook completes, a new run will fail with
> `fatal: destination path 'roles/cis' already exists and is not an empty directory.`

I'll fix this to skip the cloning and creating files steps if the folder is already present.

**Comment by awailly** [comment]
The file `Python.h` is missing without python-dev and ansible compilation from pip here.

I am testing on Ubuntu 14.04 official cloud images. By apt-get upgrade I meant the installation of new packages with apt-get.

I will test again when you push the new code and keep you updated!

**Comment by pchaigno** [comment]
I'm able to reproduce all of the issues! (not sure I should be happy about it...)

Issues with `python-dev` and `markupsafe` only happens with Ubuntu Server before installing any GUI. I'll open a separate issue to sort this out.

We can continue debugging the other issue here as it is blocking for this pull request.
The issue seems to be that Bash displays [those lines](https://github.com/awailly/cis-ubuntu-ansible/blob/install/get.sh#L15-L30) instead of executing them, the following lines are somehow skipped and then it continues installing the packages from the beginning (`python-pip`, `git`, etc.).
Also, this only happens if pipping from `curl` and if not using a redirect. The following commands works perfectly:

```
$ curl -sSL http://git.io/vZw8S | bash > output.txt
```

```
$ curl -sSL http://git.io/vZw8S > tmp.sh
$ chmod a+x tmp.sh
$ cat tmp.sh | bash
```

Any help welcome!

**Comment by awailly** [comment]
I did not like the piping curl into bash thing, and now I have a reason : http://www.seancassidy.me/dont-pipe-to-your-shell.html. What do you thing about the following command? 

```
curl -sSL http://git.io/vZw8S /tmp/cis-ubuntu-install.sh && bash /tmp/cis-ubuntu-install.sh
```

Still a race condition on /tmp, but more acceptable.

**Comment by pchaigno** [comment]
To prevent this issue from happening we could also put the code into a subroutine or buffer the file using `stdbuf`.

**Comment by pchaigno** [comment]
I refactored the code to use subroutines.

There's still the previous bug (with the code being displayed instead of executed). We could avoid it using the command you proposed: `curl -sSL http://git.io/vZw8S > /tmp/cis-ubuntu-install.sh && bash /tmp/cis-ubuntu-install.sh`. Do you think I should change the README to use that command so that we can merge this for the pre-release? (I still want to fix this in the long term.)

**Comment by awailly** [comment]
Excellent idea. I also want to fix it, but this feature is a must-have for
the release. Thus I will merge it as soon as I can test it (I want to try
some integration with the CI).

**Comment by pchaigno** [comment]
I updated the README.

I also moved the instructions for dependencies installation to the `Manual Installation` section since they are not needed in the case of the `One liner installation`.

**Pull request merged**
