### PR TITLE
Fix #101 errors with undefined variable

### LINKED ISSUE #101: 2.17.2 Set Sticky Bit on All World-Writable Directories fails is no files found
If section 2.17 is skipped section 2.17.2 will result in the following error:

```
TASK: [cis | 2.17.2 Set Sticky Bit on All World-Writable Directories (Scored)] ***
fatal: [10.0.139.156] => with_items expects a list or a set
fatal: [10.0.136.223] => with_items expects a list or a set
```

This is really a general problem with ansible (at least with 1.9) in that even though a task is skipped its with_items is still evaluated.

### PR DESCRIPTION
**Pull request by pchaigno**
As discussed in #102, there are errors with undefined variables under Ansible 1.9.

When running in check mode, _check tasks_ without an `always-run` statement are not executed.
As a consequence, subsequent _main tasks_ error on undefined variables.

This pull request adds an `always_run` statement to all _check tasks_

### CODE REVIEW

**Comment by pchaigno** [comment]
@memelet Could you check that this fixes any error for you with Ansible 1.9?

**Comment by memelet** [comment]
Well, we've upgraded to 2.1. I was not hard, but certainly tedious. I don't think I could run our playbooks on 1.9 any more.

**Comment by pchaigno** [comment]
Okay, I'll test on my side with tags ;)

**Comment by pchaigno** [comment]
@awailly This should fix #101 (tested with Ansible 1.9.1 under Ubuntu 14.04).

**Comment by awailly** [comment]
All good then, merging.

**Pull request merged**
