### PR TITLE
Add documentation about SSH Fingerprint issue

### PR DESCRIPTION
**Pull request by sabriedd**

### CODE REVIEW

**Comment by pchaigno** [comment]
@SpoonBoy So no `local_action`? :disappointed:

**Comment by awailly** [comment]
@SpoonBoy please comment @pchaigno answer before merging.

**Comment by sabriedd** [comment]
@pchaigno : Because we're using ansible to manage openstack VM, the facts gathered when running the playbook returns me the wrong IP address (not the floating one). So I can't do a local_action to remove the fingerprint.
If we manage to get the floating IP somewhere (maybe in the var file ?) I could remove the fingerprint.

**Comment by pchaigno** [comment]
I see :+1:

**Pull request merged**
