### PR TITLE
Fix rsyslog section numbering to match CIS doc

### PR DESCRIPTION
**Pull request by eastokes**
I noticed this task was mis-numbered, checked against the CIS guidance pdf.

### CODE REVIEW

**Comment by pchaigno** [comment]
I have `8.2.5 Configure rsyslog to Send Logs to a Remote Log Host (Scored)` in my version (CIS Ubuntu 14.04 LTS Server Benchmark v1.0.0). Do you have a newer version?

**Comment by eastokes** [comment]
@pchaigno Yes, 8.2.5 is that section, but this task block I've renumbered is for 8.2.2. 8.2.5 comes later in tasks/section_08_level1.yml and is numbered correctly. 

8.2.2 specifies "Set the proper start conditions in /etc/init/rsyslog.conf: start on filesystem"

**Comment by pchaigno** [comment]
Oh, right! Then [#L20](https://github.com/awailly/cis-ubuntu-ansible/blob/a58e5e6a7e5184c80cf44ff600e8eea60d32cba5/tasks/section_08_level1.yml#L20) should be renamed to `8.2.2.1 Ensure the rsyslog Service is activated (check) (Scored)` and [#L31](https://github.com/awailly/cis-ubuntu-ansible/blob/a58e5e6a7e5184c80cf44ff600e8eea60d32cba5/tasks/section_08_level1.yml#L31) to `8.2.2.2 Ensure the rsyslog Service is activated (Scored)`.

**Comment by eastokes** [comment]
Good call, I'll update this PR

**Comment by pchaigno** [comment]
Could you change the names too please? (They're also incorrect.)

**Comment by eastokes** [comment]
My bad, should be good now

**Comment by pchaigno** [comment]
Could you also add `(check)` for `8.2.2.1 Ensure the rsyslog Service is activated (check) (Scored)`? :innocent:

**Comment by pchaigno** [comment]
Thanks @eastokes!

**Pull request merged**
