### PR TITLE
Benchmark fails: 10.1.2 Set Password Change Minimum Number of Days

### PR DESCRIPTION
**Pull request by cpliakas**
I noticed that after running this role, the `10.1.2 Set Password Change Minimum Number of Days` fails the benchmark fails according to the The CIS-CAT Benchmark Assessment Tool. Digging in deeper, the task was being skipped because the conditional check failed, despite the regex correctly pulling out the `0`. Verbose output is pasted below:

```
TASK [10.1.2.1 Set Password Change Minimum Number of Days (check) (Scored)] ****
task path: /root/playbook.yml:6
ok: [127.0.0.1] => {"changed": false, "cmd": ["grep", "-oP", "(?<=^PASS_MIN_DAYS\\s)[0-9]+", "/etc/login.defs"], "delta": "0:00:00.001806", "end": "2016-09-07 10:20:14.970025", "rc": 0, "start": "2016-09-07 10:20:14.968219", "stderr": "", "stdout": "0", "stdout_lines": ["0"], "warnings": []}

TASK [10.1.2.2 Set Password Change Minimum Number of Days (Scored)] ************
task path: /root/playbook.yml:16
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}TASK [10.1.2.1 Set Password Change Minimum Number of Days (check) (Scored)] ****
task path: /root/playbook.yml:6
ok: [127.0.0.1] => {"changed": false, "cmd": ["grep", "-oP", "(?<=^PASS_MIN_DAYS\\s)[0-9]+", "/etc/login.defs"], "delta": "0:00:00.001806", "end": "2016-09-07 10:20:14.970025", "rc": 0, "start": "2016-09-07 10:20:14.968219", "stderr": "", "stdout": "0", "stdout_lines": ["0"], "warnings": []}

TASK [10.1.2.2 Set Password Change Minimum Number of Days (Scored)] ************
task path: /root/playbook.yml:16
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

Casting the `pass_min_days.stdout_lines` value to an int seems to fix the condition. I found 2 other instances where numeric comparisons are done, so I cast those to ints as well.

### CODE REVIEW

**Comment by cpliakas** [comment]
Not ready to merge, the PR now causes `10.1.1 Set Password Expiration Days` to fail.

**Comment by cpliakas** [comment]
Most recent commit allows `10.1.1 Set Password Expiration Days` to pass. No idea what the difference is that would cause one to require a case to an int and another to not.

**Comment by awailly** [comment]
@cpliakas are we ready to merge? The travis test seems good with the `int` cast. Can you paste the error you have if they are still present?

**Comment by pchaigno** [comment]
@awailly I'd like to checkout the error with the integer cast before we merge.

**Comment by cpliakas** [comment]
@awailly @pchaigno Sorry about the pull request noise, let me try to explain where things are at. There shouldn't be any errors in the pull request as it is, and in addition to the Travis CI tests passing I have been using this patch for the past few days with no problems. I am getting a clean scan for the 10. section from the CIS CAT tool.

The problem I was having was with the `10.1.1.2 Set Password Expiration Days (Scored)` task, which was removed in the commit at 97f4e45416. But, although the tests are passing, it is a bit confusing to me as to why the int cast doesn't work for that task, but does for the `10.1.2.2 Set Password Change Minimum Number of Days (Scored)` and `10.1.3.2 Set Password Expiring Warning Days (Scored)` tasks.

So although everything is passing and working for me with this patch applied, that inconsistency is a bit concerning to me. Maybe there is something obvious I am missing since I am an Ansible noob.

**Review by s01ipsist — COMMENTED** [review]
https://github.com/awailly/cis-ubuntu-ansible/pull/129/files
Duplicates and extends on this PR

**Comment by cpliakas** [comment]
Great! Should we close this PR in favor of #129 then?

**Comment by s01ipsist** [comment]
I believe so

**Pull request closed without merging**
