### PR TITLE
Option to enable TCP syncookies

### LINKED ISSUE #30: TCP Syncookies support
When I launch the playbook on an Ubuntu 14.04 in Docker:

```
TASK: [cis-ubuntu-ansible | 7.2.8 Enable TCP SYN Cookies (Scored)] ************ 
failed: [localhost] => {"failed": true}
msg: Failed to reload sysctl: sysctl: setting key "fs.suid_dumpable": Read-only file system
sysctl: setting key "kernel.randomize_va_space": Read-only file system
sysctl: setting key "net.ipv4.ip_forward": Read-only file system
sysctl: setting key "net.ipv4.conf.all.send_redirects": Read-only file system
sysctl: sett
ing key "net.ipv4.conf.default.send_redirects": Read-only file system
sysctl: setting key "net.ipv4.conf.all.accept_source_route": Read-only file system
sysctl: setting key "net.ipv4.conf.default.accept_source_route": Read-only file system
sysctl: setting key "net.ipv4.conf.all.accept_redirects": Read-only file system
sysctl: setting key "net.ipv4.conf.default.accept_redirects": Read-only file system
sysctl: setting key "net.ipv4.conf.all.secure_redirects": Read-only file system
sysctl: setting key "net.ipv4.conf.default.secure_redirects": Read-only file system
sysctl: setting key "net.ipv4.conf.all.log_martians": Read-only file system
sysctl: setting key "net.ipv4.conf.default.log_martians": Read-only file system
sysctl: setting key "net.ipv4.icmp_echo_ignore_broadcasts": Read-only file system
sysctl: setting key "net.ipv4.icmp_ignore_bogus_error_responses": Read-only file system
sysctl: setting key "net.ipv4.conf.all.rp_filter": Read-only file system
sysctl: setting key "net.ipv4.conf.default.rp_filter": Read-only file system
sysctl: cannot stat /proc/sys/net/ipv4/tcp_syncookies: No such file or directory
```

Looks like there is no TCP syncookies support in the kernel. Is it mandatory for the CIS rules? If it is, we'll probably need to add an option to skip it in Docker. Otherwise, it should detect that the kernel doesn't support it and skip this task automatically...

EDIT: Docker build: https://registry.hub.docker.com/u/pchaigno/cis-ubuntu-ansible/build_id/63371/code/bzpufxc6renmdzgkhyrdy7b/

### PR DESCRIPTION
**Pull request by pchaigno**
This PR adds an option to enable TCP syncookies.
Fixes #30.

### CODE REVIEW

**Comment by awailly** [comment]
This PR underlines the question of different environment support over time. When we will have dozens of environment files (i.e. travis_default.yml, drone_default.yml) it will be time consuming to update all of them.

I see a solution with a static `defaults/main.yml` and specific files taking precedence in `vars/`.

**Comment by pchaigno** [comment]
> When we will have dozens of environment files (i.e. travis_default.yml, drone_default.yml)

We'll only have one per CI + one for Docker tough, right?
<br>

> I see a solution with a static defaults/main.yml and specific files taking precedence in vars/.

Does that mean we would have to write them "on-the-fly" in the CI scripts?

**Comment by awailly** [comment]
We will only have one per CI in the repository, but if forks want to follow our master every new variable has a strong impact.

I don't think we have to write them on-the-fly, I am editing the master to see if it is possible. Fortunately it will be easier to write new environment files. I will need your PR to remove modifications over `defaults/travis_defaults.yml` and `defaults/drone_defaults.yml`, as they are not needed anymore.

**Comment by pchaigno** [comment]
@awailly I think we can merge this. Coveralls isn't going to respond now :/

**Pull request merged**
